# Allow Travis to use container based infrastructure
sudo: false
language: go
arch:
  - amd64
  - ppc64le
go:
  - 1.10.x
  - 1.11.x

install:
  - go get -u golang.org/x/net/websocket
  - go get -u golang.org/x/lint/golint

script:
  - golint ./...
  - go test -v ./... --race
